### ISSUE TITLE
CAN NOT see pancake V2 LP Token

### ISSUE THREAD

**Issue by mmmmmagina** [ellipsis-finance/ellipsis#9]
Hello , I add some liquidity to market pair EPS-BNB on https://exchange.pancakeswap.finance/#/pool. but I can't see the amount at web page https://www.ellipsis.finance/stake. It is that staking just support the pancake V1 LP token? please tell me when to support if it will be.  because currently, Pancake only supports adding liquidity to V2 and got V2 LP-Token. 

![image](https://user-images.githubusercontent.com/4277487/117250124-5414fb80-ae75-11eb-9fd1-b58ec842572a.png)

**Comment by mmmmmagina** [comment]
@mashup-artist @0xsis

**Comment by 0xsis** [comment]
Staking only supports v1 token, will add a note to say so

**Comment by mmmmmagina** [comment]
@0xsis  will you support V2?  pancake could not add liquidity to V1 contract.
